import "../style.css"

export default function home () {
     return `
  <div class="root">
      <div class="container">
           <div class="header">
                 <h2>
                     Show Result
                 </h2>
           </div>
           <div class="searchContainer">
                <form class="searchForm">
                     <div class="searchInput searchInput-col-1">
                         <label for="startDate">
                            Start Date:
                        </label>
                         <input type="date" id="startDate" required>
                     </div>
                     <div class="searchInput searchInput-col-2">
                         <label for="endDate">
                            end Date:
                         </label>
                         <input type="date" id="startDate" required>
                     </div>
                </form>
                <button type="button">
                      <span>
                          <i class="fa-solid fa-magnifying-glass"></i>
                      </span>
                      <span>
                         search
                      </span>
                </button> 
           </div>
           <p class="resultDateTitle">Result of The Date 
               <span class="resultDate"> 24/03/2025</span>
           </p>
           <div class="resultContainer">
               <table>
                   <thead>
                        <tr>
                           <th>Date</th>
                           <th>Time</th>
                           <th>XA</th>
                           <th>XB</th>
                           <th>XC</th>
                           <th>XD</th>
                           <th>XE</th>
                           <th>XF</th>
                           <th>XG</th>
                           <th>XH</th>
                           <th>XI</th>
                           <th>XJ</th>
                        </tr>   
                   </thead>
                   <tbody>
                        <tr>
                           <td>25-03-2025</td>
                           <td>09:00</td>
                           <td>XA04</td>
                           <td>XB94</td>
                           <td>XC21</td>
                           <td>XD51</td>
                           <td>XE28</td>
                           <td>XF69</td>
                           <td>XG19</td>
                           <td>XH04</td>
                           <td>XI50</td>
                           <td>XJ21</td>
                        </tr>                   
                        <tr>
                           <td>25-03-2025</td>
                           <td>09:00</td>
                           <td>XA04</td>
                           <td>XB94</td>
                           <td>XC21</td>
                           <td>XD51</td>
                           <td>XE28</td>
                           <td>XF69</td>
                           <td>XG19</td>
                           <td>XH04</td>
                           <td>XI50</td>
                           <td>XJ21</td>
                        </tr>                   
                        <tr>
                           <td>25-03-2025</td>
                           <td>09:00</td>
                           <td>XA04</td>
                           <td>XB94</td>
                           <td>XC21</td>
                           <td>XD51</td>
                           <td>XE28</td>
                           <td>XF69</td>
                           <td>XG19</td>
                           <td>XH04</td>
                           <td>XI50</td>
                           <td>XJ21</td>
                        </tr>                   
                        <tr>
                           <td>25-03-2025</td>
                           <td>09:00</td>
                           <td>XA04</td>
                           <td>XB94</td>
                           <td>XC21</td>
                           <td>XD51</td>
                           <td>XE28</td>
                           <td>XF69</td>
                           <td>XG19</td>
                           <td>XH04</td>
                           <td>XI50</td>
                           <td>XJ21</td>
                        </tr>                   
                        <tr>
                           <td>25-03-2025</td>
                           <td>09:00</td>
                           <td>XA04</td>
                           <td>XB94</td>
                           <td>XC21</td>
                           <td>XD51</td>
                           <td>XE28</td>
                           <td>XF69</td>
                           <td>XG19</td>
                           <td>XH04</td>
                           <td>XI50</td>
                           <td>XJ21</td>
                        </tr>                   
                        <tr>
                           <td>25-03-2025</td>
                           <td>09:00</td>
                           <td>XA04</td>
                           <td>XB94</td>
                           <td>XC21</td>
                           <td>XD51</td>
                           <td>XE28</td>
                           <td>XF69</td>
                           <td>XG19</td>
                           <td>XH04</td>
                           <td>XI50</td>
                           <td>XJ21</td>
                        </tr>                   
                        <tr>
                           <td>25-03-2025</td>
                           <td>09:00</td>
                           <td>XA04</td>
                           <td>XB94</td>
                           <td>XC21</td>
                           <td>XD51</td>
                           <td>XE28</td>
                           <td>XF69</td>
                           <td>XG19</td>
                           <td>XH04</td>
                           <td>XI50</td>
                           <td>XJ21</td>
                        </tr>                   
                        <tr>
                           <td>25-03-2025</td>
                           <td>09:00</td>
                           <td>XA04</td>
                           <td>XB94</td>
                           <td>XC21</td>
                           <td>XD51</td>
                           <td>XE28</td>
                           <td>XF69</td>
                           <td>XG19</td>
                           <td>XH04</td>
                           <td>XI50</td>
                           <td>XJ21</td>
                        </tr>                   
                        <tr>
                           <td>25-03-2025</td>
                           <td>09:00</td>
                           <td>XA04</td>
                           <td>XB94</td>
                           <td>XC21</td>
                           <td>XD51</td>
                           <td>XE28</td>
                           <td>XF69</td>
                           <td>XG19</td>
                           <td>XH04</td>
                           <td>XI50</td>
                           <td>XJ21</td>
                        </tr>                   
                        <tr>
                           <td>25-03-2025</td>
                           <td>09:00</td>
                           <td>XA04</td>
                           <td>XB94</td>
                           <td>XC21</td>
                           <td>XD51</td>
                           <td>XE28</td>
                           <td>XF69</td>
                           <td>XG19</td>
                           <td>XH04</td>
                           <td>XI50</td>
                           <td>XJ21</td>
                        </tr>                   
                        <tr>
                           <td>25-03-2025</td>
                           <td>09:00</td>
                           <td>XA04</td>
                           <td>XB94</td>
                           <td>XC21</td>
                           <td>XD51</td>
                           <td>XE28</td>
                           <td>XF69</td>
                           <td>XG19</td>
                           <td>XH04</td>
                           <td>XI50</td>
                           <td>XJ21</td>
                        </tr>                   
                        <tr>
                           <td>25-03-2025</td>
                           <td>09:00</td>
                           <td>XA04</td>
                           <td>XB94</td>
                           <td>XC21</td>
                           <td>XD51</td>
                           <td>XE28</td>
                           <td>XF69</td>
                           <td>XG19</td>
                           <td>XH04</td>
                           <td>XI50</td>
                           <td>XJ21</td>
                        </tr>                   
                        <tr>
                           <td>25-03-2025</td>
                           <td>09:00</td>
                           <td>XA04</td>
                           <td>XB94</td>
                           <td>XC21</td>
                           <td>XD51</td>
                           <td>XE28</td>
                           <td>XF69</td>
                           <td>XG19</td>
                           <td>XH04</td>
                           <td>XI50</td>
                           <td>XJ21</td>
                        </tr>                   
                        <tr>
                           <td>25-03-2025</td>
                           <td>09:00</td>
                           <td>XA04</td>
                           <td>XB94</td>
                           <td>XC21</td>
                           <td>XD51</td>
                           <td>XE28</td>
                           <td>XF69</td>
                           <td>XG19</td>
                           <td>XH04</td>
                           <td>XI50</td>
                           <td>XJ21</td>
                        </tr>                   
                        <tr>
                           <td>25-03-2025</td>
                           <td>09:00</td>
                           <td>XA04</td>
                           <td>XB94</td>
                           <td>XC21</td>
                           <td>XD51</td>
                           <td>XE28</td>
                           <td>XF69</td>
                           <td>XG19</td>
                           <td>XH04</td>
                           <td>XI50</td>
                           <td>XJ21</td>
                        </tr>                   
                        <tr>
                           <td>25-03-2025</td>
                           <td>09:00</td>
                           <td>XA04</td>
                           <td>XB94</td>
                           <td>XC21</td>
                           <td>XD51</td>
                           <td>XE28</td>
                           <td>XF69</td>
                           <td>XG19</td>
                           <td>XH04</td>
                           <td>XI50</td>
                           <td>XJ21</td>
                        </tr>                   
                        <tr>
                           <td>25-03-2025</td>
                           <td>09:00</td>
                           <td>XA04</td>
                           <td>XB94</td>
                           <td>XC21</td>
                           <td>XD51</td>
                           <td>XE28</td>
                           <td>XF69</td>
                           <td>XG19</td>
                           <td>XH04</td>
                           <td>XI50</td>
                           <td>XJ21</td>
                        </tr>                   
                        <tr>
                           <td>25-03-2025</td>
                           <td>09:00</td>
                           <td>XA04</td>
                           <td>XB94</td>
                           <td>XC21</td>
                           <td>XD51</td>
                           <td>XE28</td>
                           <td>XF69</td>
                           <td>XG19</td>
                           <td>XH04</td>
                           <td>XI50</td>
                           <td>XJ21</td>
                        </tr>                   
                        <tr>
                           <td>25-03-2025</td>
                           <td>09:00</td>
                           <td>XA04</td>
                           <td>XB94</td>
                           <td>XC21</td>
                           <td>XD51</td>
                           <td>XE28</td>
                           <td>XF69</td>
                           <td>XG19</td>
                           <td>XH04</td>
                           <td>XI50</td>
                           <td>XJ21</td>
                        </tr>                   
                        <tr>
                           <td>25-03-2025</td>
                           <td>09:00</td>
                           <td>XA04</td>
                           <td>XB94</td>
                           <td>XC21</td>
                           <td>XD51</td>
                           <td>XE28</td>
                           <td>XF69</td>
                           <td>XG19</td>
                           <td>XH04</td>
                           <td>XI50</td>
                           <td>XJ21</td>
                        </tr>                   
                        <tr>
                           <td>25-03-2025</td>
                           <td>09:00</td>
                           <td>XA04</td>
                           <td>XB94</td>
                           <td>XC21</td>
                           <td>XD51</td>
                           <td>XE28</td>
                           <td>XF69</td>
                           <td>XG19</td>
                           <td>XH04</td>
                           <td>XI50</td>
                           <td>XJ21</td>
                        </tr>                   
                        <tr>
                           <td>25-03-2025</td>
                           <td>09:00</td>
                           <td>XA04</td>
                           <td>XB94</td>
                           <td>XC21</td>
                           <td>XD51</td>
                           <td>XE28</td>
                           <td>XF69</td>
                           <td>XG19</td>
                           <td>XH04</td>
                           <td>XI50</td>
                           <td>XJ21</td>
                        </tr>                   
                        <tr>
                           <td>25-03-2025</td>
                           <td>09:00</td>
                           <td>XA04</td>
                           <td>XB94</td>
                           <td>XC21</td>
                           <td>XD51</td>
                           <td>XE28</td>
                           <td>XF69</td>
                           <td>XG19</td>
                           <td>XH04</td>
                           <td>XI50</td>
                           <td>XJ21</td>
                        </tr>                   
                        <tr>
                           <td>25-03-2025</td>
                           <td>09:00</td>
                           <td>XA04</td>
                           <td>XB94</td>
                           <td>XC21</td>
                           <td>XD51</td>
                           <td>XE28</td>
                           <td>XF69</td>
                           <td>XG19</td>
                           <td>XH04</td>
                           <td>XI50</td>
                           <td>XJ21</td>
                        </tr>                   
                        <tr>
                           <td>25-03-2025</td>
                           <td>09:00</td>
                           <td>XA04</td>
                           <td>XB94</td>
                           <td>XC21</td>
                           <td>XD51</td>
                           <td>XE28</td>
                           <td>XF69</td>
                           <td>XG19</td>
                           <td>XH04</td>
                           <td>XI50</td>
                           <td>XJ21</td>
                        </tr>                   
                        <tr>
                           <td>25-03-2025</td>
                           <td>09:00</td>
                           <td>XA04</td>
                           <td>XB94</td>
                           <td>XC21</td>
                           <td>XD51</td>
                           <td>XE28</td>
                           <td>XF69</td>
                           <td>XG19</td>
                           <td>XH04</td>
                           <td>XI50</td>
                           <td>XJ21</td>
                        </tr>                   
                        <tr>
                           <td>25-03-2025</td>
                           <td>09:00</td>
                           <td>XA04</td>
                           <td>XB94</td>
                           <td>XC21</td>
                           <td>XD51</td>
                           <td>XE28</td>
                           <td>XF69</td>
                           <td>XG19</td>
                           <td>XH04</td>
                           <td>XI50</td>
                           <td>XJ21</td>
                        </tr>                   
                        <tr>
                           <td>25-03-2025</td>
                           <td>09:00</td>
                           <td>XA04</td>
                           <td>XB94</td>
                           <td>XC21</td>
                           <td>XD51</td>
                           <td>XE28</td>
                           <td>XF69</td>
                           <td>XG19</td>
                           <td>XH04</td>
                           <td>XI50</td>
                           <td>XJ21</td>
                        </tr>                   
                        <tr>
                           <td>25-03-2025</td>
                           <td>09:00</td>
                           <td>XA04</td>
                           <td>XB94</td>
                           <td>XC21</td>
                           <td>XD51</td>
                           <td>XE28</td>
                           <td>XF69</td>
                           <td>XG19</td>
                           <td>XH04</td>
                           <td>XI50</td>
                           <td>XJ21</td>
                        </tr>                   
                        <tr>
                           <td>25-03-2025</td>
                           <td>09:00</td>
                           <td>XA04</td>
                           <td>XB94</td>
                           <td>XC21</td>
                           <td>XD51</td>
                           <td>XE28</td>
                           <td>XF69</td>
                           <td>XG19</td>
                           <td>XH04</td>
                           <td>XI50</td>
                           <td>XJ21</td>
                        </tr>                   
                        <tr>
                           <td>25-03-2025</td>
                           <td>09:00</td>
                           <td>XA04</td>
                           <td>XB94</td>
                           <td>XC21</td>
                           <td>XD51</td>
                           <td>XE28</td>
                           <td>XF69</td>
                           <td>XG19</td>
                           <td>XH04</td>
                           <td>XI50</td>
                           <td>XJ21</td>
                        </tr>                   
                        <tr>
                           <td>25-03-2025</td>
                           <td>09:00</td>
                           <td>XA04</td>
                           <td>XB94</td>
                           <td>XC21</td>
                           <td>XD51</td>
                           <td>XE28</td>
                           <td>XF69</td>
                           <td>XG19</td>
                           <td>XH04</td>
                           <td>XI50</td>
                           <td>XJ21</td>
                        </tr>                   
                        <tr>
                           <td>25-03-2025</td>
                           <td>09:00</td>
                           <td>XA04</td>
                           <td>XB94</td>
                           <td>XC21</td>
                           <td>XD51</td>
                           <td>XE28</td>
                           <td>XF69</td>
                           <td>XG19</td>
                           <td>XH04</td>
                           <td>XI50</td>
                           <td>XJ21</td>
                        </tr>                   
                        <tr>
                           <td>25-03-2025</td>
                           <td>09:00</td>
                           <td>XA04</td>
                           <td>XB94</td>
                           <td>XC21</td>
                           <td>XD51</td>
                           <td>XE28</td>
                           <td>XF69</td>
                           <td>XG19</td>
                           <td>XH04</td>
                           <td>XI50</td>
                           <td>XJ21</td>
                        </tr>                   
                        <tr>
                           <td>25-03-2025</td>
                           <td>09:00</td>
                           <td>XA04</td>
                           <td>XB94</td>
                           <td>XC21</td>
                           <td>XD51</td>
                           <td>XE28</td>
                           <td>XF69</td>
                           <td>XG19</td>
                           <td>XH04</td>
                           <td>XI50</td>
                           <td>XJ21</td>
                        </tr>                   
                        <tr>
                           <td>25-03-2025</td>
                           <td>09:00</td>
                           <td>XA04</td>
                           <td>XB94</td>
                           <td>XC21</td>
                           <td>XD51</td>
                           <td>XE28</td>
                           <td>XF69</td>
                           <td>XG19</td>
                           <td>XH04</td>
                           <td>XI50</td>
                           <td>XJ21</td>
                        </tr>                   
                        <tr>
                           <td>25-03-2025</td>
                           <td>09:00</td>
                           <td>XA04</td>
                           <td>XB94</td>
                           <td>XC21</td>
                           <td>XD51</td>
                           <td>XE28</td>
                           <td>XF69</td>
                           <td>XG19</td>
                           <td>XH04</td>
                           <td>XI50</td>
                           <td>XJ21</td>
                        </tr>                   
                   </tbody> 
               </table>
           </div>           
      </div>
  </div>
  `
}